#!/bin/bash
#
# Hack rsync local changes into the hermes install in the 'sdc' zone on the
# given HN.
#

#set -o xtrace
set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
NODE=$1

if [[ -z "$SDC_ZONE" ]]; then
    SDC_ZONE=$(ssh $NODE "/opt/smartdc/bin/sdc-vmapi /vms" 2>/dev/null \
        | json -H -c 'this.tags && this.tags.smartdc_role === "sdc"' \
            -c 'this.state === "running"' 0.uuid)
fi
echo "SDC_ZONE: $SDC_ZONE"

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node --exclude build"
else
    # Clean node_modules everytime.
    ssh $NODE rm -rf /zones/$SDC_ZONE/root/opt/smartdc/hermes/node_modules
fi

rsync -av ${TOP}/proto/opt/smartdc/hermes/ \
    $NODE:/zones/$SDC_ZONE/root/opt/smartdc/hermes/ \
    $extraOpts

state=$(ssh ${NODE} svcs -z ${SDC_ZONE} -H -o state hermes)
if [[ "$state" == "maintenance" ]]; then
    ssh ${NODE} svcadm -z ${SDC_ZONE} clear hermes
else
    ssh ${NODE} svcadm -z ${SDC_ZONE} restart hermes
fi
ssh ${NODE} svcadm -z ${SDC_ZONE} restart config-agent
